//
// Created by 钱晨 on 1/30/21.
//

#ifndef META_INFANTRY_VEHICLE_SENTRY_LITE_H
#define META_INFANTRY_VEHICLE_SENTRY_LITE_H

#endif //META_INFANTRY_VEHICLE_SENTRY_LITE_H

#define CHASSIS_FR_CAN_ID      0
#define CHASSIS_FL_CAN_ID      2
#define GIMBAL_YAW_CAN_ID       4
#define GIMBAL_PITCH_CAN_ID     5
#define GIMBAL_FW_L_CAN_ID      1
#define GIMBAL_FW_R_CAN_ID      3
#define GIMBAL_BULLET_CAN_ID    6

#define CHASSIS_FR_MOTOR_TYPE   (CANInterface::M3508)
#define CHASSIS_FL_MOTOR_TYPE   (CANInterface::M3508)
#define GIMBAL_YAW_MOTOR_TYPE   (CANInterface::GM6020)
#define GIMBAL_PITCH_MOTOR_TYPE (CANInterface::M2006)
#define GIMBAL_FW_L_MOTOR_TYPE  (CANInterface::M3508)
#define GIMBAL_FW_R_MOTOR_TYPE  (CANInterface::M3508)
#define GIMBAL_BULLET_MTR_TYPE  (CANInterface::M2006)

#define CHASSIS_FR_CHANNEL      (SchassisIF::can_channel_1)
#define CHASSIS_FL_CHANNEL      (SchassisIF::can_channel_1)
#define GIMBAL_YAW_CHANNEL      (SGimbalIF::can_channel_1)
#define GIMBAL_PITCH_CHANNEL    (SGimbalIF::can_channel_1)
#define GIMBAL_FW_L_CHANNEL     (SGimbalIF::can_channel_1)
#define GIMBAL_FW_R_CHANNEL     (SGimbalIF::can_channel_1)
#define GIMBAL_BULLET_CHANNEL   (SGimbalIF::can_channel_1)

#define CHASSIS_MOTOR_CONFIG \
{ {CHASSIS_FR_CHANNEL, CHASSIS_FR_CAN_ID, CHASSIS_FR_MOTOR_TYPE}, \
  {CHASSIS_FL_CHANNEL, CHASSIS_FL_CAN_ID, CHASSIS_FL_MOTOR_TYPE} }

#define GIMBAL_MOTOR_CONFIG \
{ {GIMBAL_YAW_CHANNEL,      GIMBAL_YAW_CAN_ID,      GIMBAL_YAW_MOTOR_TYPE}, \
  {GIMBAL_PITCH_CHANNEL,    GIMBAL_PITCH_CAN_ID,    GIMBAL_PITCH_MOTOR_TYPE}, \
  {GIMBAL_BULLET_CHANNEL,   GIMBAL_BULLET_CAN_ID,   GIMBAL_BULLET_MTR_TYPE}, \
  {GIMBAL_FW_L_CHANNEL,     GIMBAL_FW_L_CAN_ID,     GIMBAL_FW_L_MOTOR_TYPE}, \
  {GIMBAL_FW_R_CHANNEL,     GIMBAL_FW_R_CAN_ID,     GIMBAL_FW_R_MOTOR_TYPE} }

#define SHOOT_PID_PITCH_A2V_KP 10.0f  // a number large enough, see shoot speed note at ShootSKD
#define SHOOT_PID_PITCH_A2V_KI 0.0f
#define SHOOT_PID_PITCH_A2V_KD 2.0f
#define SHOOT_PID_PITCH_A2V_I_LIMIT 0.0f
#define SHOOT_PID_PITCH_A2V_OUT_LIMIT 360.0f  // will be replaced, see shoot speed note at ShootSKD
#define GIMBAL_PID_PITCH_A2V_PARAMS \
    {SHOOT_PID_PITCH_A2V_KP, SHOOT_PID_PITCH_A2V_KI, SHOOT_PID_PITCH_A2V_KD, \
    SHOOT_PID_PITCH_A2V_I_LIMIT, SHOOT_PID_PITCH_A2V_OUT_LIMIT}

#define SHOOT_PID_PITCH_V2I_KP 55.0f
#define SHOOT_PID_PITCH_V2I_KI 10.0f
#define SHOOT_PID_PITCH_V2I_KD 0.0f
#define SHOOT_PID_PITCH_V2I_I_LIMIT 8000.0f
#define SHOOT_PID_PITCH_V2I_OUT_LIMIT 8000.0f
#define GIMBAL_PID_PITCH_V2I_PARAMS \
    {SHOOT_PID_PITCH_V2I_KP, SHOOT_PID_PITCH_V2I_KI, SHOOT_PID_PITCH_V2I_KD, \
    SHOOT_PID_PITCH_V2I_I_LIMIT, SHOOT_PID_PITCH_V2I_OUT_LIMIT}

#define SHOOT_PID_BULLET_LOADER_V2I_KP 55.0f
#define SHOOT_PID_BULLET_LOADER_V2I_KI 20.0f
#define SHOOT_PID_BULLET_LOADER_V2I_KD 0.0f
#define SHOOT_PID_BULLET_LOADER_V2I_I_LIMIT 10000.0f
#define SHOOT_PID_BULLET_LOADER_V2I_OUT_LIMIT 10000.0f
#define SHOOT_PID_BULLET_LOADER_V2I_PARAMS \
    {SHOOT_PID_BULLET_LOADER_V2I_KP, SHOOT_PID_BULLET_LOADER_V2I_KI, SHOOT_PID_BULLET_LOADER_V2I_KD, \
    SHOOT_PID_BULLET_LOADER_V2I_I_LIMIT, SHOOT_PID_BULLET_LOADER_V2I_OUT_LIMIT}

/// Gimbal and Shoot PID Parameters
#define GIMBAL_PID_YAW_A2V_KP 12.0f
#define GIMBAL_PID_YAW_A2V_KI 0.0f
#define GIMBAL_PID_YAW_A2V_KD 0.08f
#define GIMBAL_PID_YAW_A2V_I_LIMIT 1000.0f
#define GIMBAL_PID_YAW_A2V_OUT_LIMIT 2000.0f
#define GIMBAL_PID_YAW_A2V_PARAMS \
    {GIMBAL_PID_YAW_A2V_KP, GIMBAL_PID_YAW_A2V_KI, GIMBAL_PID_YAW_A2V_KD, \
    GIMBAL_PID_YAW_A2V_I_LIMIT, GIMBAL_PID_YAW_A2V_OUT_LIMIT}

#define GIMBAL_PID_YAW_V2I_KP 36.0f
#define GIMBAL_PID_YAW_V2I_KI 0.9f
#define GIMBAL_PID_YAW_V2I_KD 0.0f
#define GIMBAL_PID_YAW_V2I_I_LIMIT 2500.0f
#define GIMBAL_PID_YAW_V2I_OUT_LIMIT 10000.0f
#define GIMBAL_PID_YAW_V2I_PARAMS \
    {GIMBAL_PID_YAW_V2I_KP, GIMBAL_PID_YAW_V2I_KI, GIMBAL_PID_YAW_V2I_KD, \
    GIMBAL_PID_YAW_V2I_I_LIMIT, GIMBAL_PID_YAW_V2I_OUT_LIMIT}


#define SHOOT_PID_FW_LEFT_V2I_KP 26.0f
#define SHOOT_PID_FW_LEFT_V2I_KI 0.1f
#define SHOOT_PID_FW_LEFT_V2I_KD 0.02f
#define SHOOT_PID_FW_LEFT_V2I_I_LIMIT 2000.0f
#define SHOOT_PID_FW_LEFT_V2I_OUT_LIMIT 6000.0f
#define SHOOT_PID_FW_LEFT_V2I_PARAMS \
    {SHOOT_PID_FW_LEFT_V2I_KP, SHOOT_PID_FW_LEFT_V2I_KI, SHOOT_PID_FW_LEFT_V2I_KD, \
    SHOOT_PID_FW_LEFT_V2I_I_LIMIT, SHOOT_PID_FW_LEFT_V2I_OUT_LIMIT}

/// Chassis PID Parameters
#define CHASSIS_PID_V2I_KP 26.0f
#define CHASSIS_PID_V2I_KI 0.1f
#define CHASSIS_PID_V2I_KD 0.02f
#define CHASSIS_PID_V2I_I_LIMIT 2000.0f
#define CHASSIS_PID_V2I_OUT_LIMIT 6000.0f
#define CHASSIS_PID_V2I_PARAMS \
    {CHASSIS_PID_V2I_KP, CHASSIS_PID_V2I_KI, CHASSIS_PID_V2I_KD, \
    CHASSIS_PID_V2I_I_LIMIT, CHASSIS_PID_V2I_OUT_LIMIT}