//
// Created by 钱晨 on 1/30/21.
//

#ifndef META_INFANTRY_VEHICLE_SENTRY_LITE_H
#define META_INFANTRY_VEHICLE_SENTRY_LITE_H

#endif //META_INFANTRY_VEHICLE_SENTRY_LITE_H

#define CHASSIS_FR_CAN_ID      2
#define CHASSIS_FL_CAN_ID      3

#define CHASSIS_FR_MOTOR_TYPE  (CANInterface::M3508)
#define CHASSIS_FL_MOTOR_TYPE  (CANInterface::M3508)

#define CHASSIS_FR_CHANNEL      (SchassisIF::can_channel_1)
#define CHASSIS_FL_CHANNEL      (SchassisIF::can_channel_1)

#define CHASSIS_MOTOR_CONFIG \
{ {CHASSIS_FR_CHANNEL, CHASSIS_FR_CAN_ID, CHASSIS_FR_MOTOR_TYPE}, \
  {CHASSIS_FL_CHANNEL, CHASSIS_FL_CAN_ID, CHASSIS_FL_MOTOR_TYPE}  }

/// Chassis PID Parameters
#define CHASSIS_PID_V2I_KP 26.0f
#define CHASSIS_PID_V2I_KI 0.1f
#define CHASSIS_PID_V2I_KD 0.02f
#define CHASSIS_PID_V2I_I_LIMIT 2000.0f
#define CHASSIS_PID_V2I_OUT_LIMIT 6000.0f
#define CHASSIS_PID_V2I_PARAMS \
    {CHASSIS_PID_V2I_KP, CHASSIS_PID_V2I_KI, CHASSIS_PID_V2I_KD, \
    CHASSIS_PID_V2I_I_LIMIT, CHASSIS_PID_V2I_OUT_LIMIT}